
version: "3.4"
services:
  migrate:
    image: migrate/migrate:v4.15.2
    profiles: ["tools"]
    volumes:
      - ./db/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgresql://root:1dzjA7F0BA8QwXeTRXw2@bank.c3y0equmgn8w.eu-west-3.rds.amazonaws.com:5432/bank",
      ]
    command: ["up"]
    restart: on-failure

