version: "3.4"
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=bank
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate:v4.15.2
    profiles: ["tools"]
    volumes:
      - ./db/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgresql://root:secret@db:5432/bank?sslmode=disable",
      ]
    command: ["up"]
    links:
      - db
    restart: on-failure
volumes:
  db:
    driver: local
